name: Notify IRC

on:
  push:
  issues:
    types:
      - opened
      - edited
      - closed
  issue_comment:
  pull_request:
  discussion:
    types:
      - created
      - edited
      - closed
      - answered
  discussion_comment:
  create:
  delete:

jobs:
  notify-irc:
    runs-on: ubuntu-latest

    steps:
      - name: Notify IRC
        uses: openzfsonwindows/notify-irc@v1
        with:

          channel: "#IRC4Fun"
          server: "irc.irc4fun.net"
          nickname: "GitHub"
          sasl_password: ${{ secrets.SASLPASS }}
          ansicolor: "false"
          eventpath: ${{ github.event_path }}
